Homework1
made-ml-in-prod-2021/asv715 pull request #3
Opened 2021-05-09 12:08 UTC by asv715

Основной питонячий код проекта находится в ml_project/ml_process и разделен по модулям. Все манипуляции с пайплайнами конфигурируются с помощью yml-файлов (приведено две конфигурации для LogisticRegression и RandomForestClassifier), в которых настройки разбиты на секции, которые при запуске перекладываются в Data-классы. Процессинг фичей вынесен в отдельный класс, рядом с ним находится простой кастомный трансформер, который полиномиалит фичи. В проекте настроен логгер, который также конфигурируется с помощью yml-файла, логи пишутся в папку ml_project/logs. В папку ml_project/models записываются файлы с моделями, метриками и предсказаниями (функции сохранения метрик и предсказаний вынесены отдельно). Модули и функции снабжены докстрингами и объявлениями типов. Для тестов заведены фикстуры, в числе которых есть генерация фейкового датасета, но также есть выборка в файле sample.csv для проверки корректности чтения из файла. Тесты также типизированы, ассерты содержат сообщения, есть проверка выбрасывания исключения при указании неверного типа модели. Настроены Github Actions, но при прогоне линтера они отдают ошибку, хотя линтер выдает около 8 баллов.

Самопроверка:

- Ветка названа homework1, код находится в папке ml_project (1 балл)
- В описании к пулл-реквесту описаны основные решения (2 балла)
- Выполнено небольшое EDA, ноутбук закоммичен в папку notebooks (2 баллов)
- Проект имеет модульную структуру (2 баллов)
- Использованы логгеры (2 балла)
- Написаны тесты на отдельные модули и на прогон всего пайплайна (3 баллов)
- Для тестов генерируются синтетические данные небольшой самописной фикстурой (3 баллов)
- Обучение модели конфигурируется с помощью конфигов в yaml, закоммичены 2 корректные конфигурации (3 балла)
- Используются датаклассы для сущностей из конфига (3 балла)
- В дополнение к стандартным трансформерам написан один свой и тесты для него (3 балла)
- Процесс обучения модели описан Readme (3 балла)
- Написана функция predict, которая для обученной модели получает предсказания на тестовой выборке и записывает в файл. Команда для запуска описана в Readme (3 балла)
- Настроен CI(прогон тестов и линтера) на основе github actions (3 балла)
- Проведена самооценка (1 балл)

Итого: 34 балла

2021-05-10 01:06 UTC, ekhusainov reviewed
- чуток подробнее бы расписать readme и добавить файлы на гит, без которых программа не запускается. За это тоже можно минус один сделать.
- CI положительно бы завершить хотя бы один workflow (если удастся, то следующий пункт скорее всего автоматом закроется). За это можно убрать 1 балл, так как остальное там работает.
- PEP8, много замечаний по кодстайлу.

34 - 2 = 32 балла. Но можно и 34 оставить, особенно если поправит описанное)

2021-05-12 11:47 UTC, asv715 commented on ml_project/README.md
> +`config_path` - путь до конфигурационного файла в yml-формате, `model_path` - путь до файла с обученной моделью в pkl-формате, `test_sample_path` - путь до файла с тестовой выборкой
Добавил примеры запуска с конкретными путями, добавил папку logs, добавил печать метрик в stdout, положил файл с тестовой выборкой. Спасибо

2021-05-12 11:47 UTC, asv715 commented on ml_project/README.md
> +`pytest tests`
Добавил флаги

2021-05-12 11:48 UTC, asv715 commented on ml_project/README.md
> +`pylint ml_process`
Поправил ошибки

2021-05-12 11:48 UTC, asv715 commented on ml_project/ml_process/entities/feature_params.py
> +    use_log_trick: bool = field(default=False)
Ага, пропустил

2021-05-12 11:48 UTC, asv715 commented on ml_project/ml_process/utils/logger.py
> +
Поправил

2021-05-12 11:48 UTC, asv715 commented on ml_project/ml_process/train_pipeline.py
> +    logger.info(f"Data shape is {data.shape}")
Не знал про это. Спасибо, поправил

2021-05-12 11:52 UTC, asv715 commented on .github/workflows/ci-actions.yml
> +          args: cd ml_project && pip install -e . && pylint ml_process
Поправил, теперь проходит workflow

2021-05-12 11:52 UTC, asv715 commented
> У вас фейлится github actions

Поправил

2021-05-21 15:38 UTC, Mikhail-M requested changes
удалите ради бога все .pyc

2021-05-21 16:09 UTC, Mikhail-M approved these changes
Баллы: 34

2021-05-21 16:22 UTC, merged